name: Python CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging - List files
      run: ls -l

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run tests
      run: python tests.py
